/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hasDisplay(): boolean
export function setBrightness(percent: number): void
export function getBrightness(): number
